spring.application.name=recipeapp
spring.profiles.active=local-postgre
# spring.profiles.active=h2
spring.datasource.url=jdbc:postgresql://localhost:5432/recipeapp
spring.datasource.username=postgres
spring.datasource.password=Heippa_123
spring.datasource.driver-class-name=org.postgresql.Driver