spring.application.name=recipeapp
#spring.profiles.active=local-postgre
#spring.profiles.active=h2
# spring.datasource.url=jdbc:postgresql://localhost:5432/recipeapp
spring.datasource.username=recipedata_blri_user
spring.datasource.password=7nz7XzyUgCoEBaY6xHr4uR6WL4pq663z
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.sql.init.mode=always
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://dpg-d7ehugv7f7vs738r5js0-a.frankfurt-postgres.render.com/recipedata_blri?sslmode=require
spring.jpa.defer-datasource-initialization=true