spring.application.name=recipeapp
#spring.profiles.active=local-postgre
#spring.profiles.active=h2
# spring.datasource.url=jdbc:postgresql://localhost:5432/recipeapp
spring.datasource.url=jdbc:postgresql://@dpg-d7ehugv7f7vs738r5js0-a.frankfurt-postgres.render.com/recipedata_blri
spring.datasource.username=${RENDER_USERNAME}
spring.datasource.password=${RENDER_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect