spring.application.name=recipeapp
 
spring.jpa.show-sql=true

spring.data.rest.base-path=/api
 
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
 
spring.datasource.url=jdbc:postgresql://localhost:5432/recipeapp
spring.datasource.username=postgres
spring.datasource.password=Heippa_123
 
#JPA/hibernate ei tee muutoksia ulkoiseen kantaan none arvolla
spring.jpa.hibernate.ddl-auto=none