spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.sql.init.data-locations=classpath:sqlScript.sql
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

server.port=${PORT:8080}